//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSpace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkSpace()
        {
            this.WS_User_Roles = new HashSet<WS_User_Roles>();
        }
    
        public int ID { get; set; }
        public string WorkSpaceName { get; set; }
        public string Description { get; set; }
        public string Bilimail { get; set; }
        public string ImageWS { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS_User_Roles> WS_User_Roles { get; set; }
    }
}
